### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by oppsec** [march0s1as/CheckThisPass#2]
Hello marchosias!!!!! can you add the hacktoberfest tag on your repository???? THANK YOU!!!! :heart: :hear_no_evil: 

![image](https://user-images.githubusercontent.com/50470310/135761748-f73c6cae-bfed-46a8-93e2-536564194a56.png)

**Comment by march0s1as** [comment]
ok daddy!

**Comment by oppsec** [comment]
omg you're so dumb! you need to add a TAG not a LINK dumb ass bitch

**Comment by oppsec** [comment]
![image](https://user-images.githubusercontent.com/50470310/135886070-902682e7-daac-424e-9309-9eadf0355f09.png)

**Comment by march0s1as** [comment]
fuck you lamer
